### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by blackpintz** [blackpintz/Capstone-GroupTransactions#2]

**Comment by teekaytech** [comment]
Keep up the nice work, Rose. You're almost there :muscle:

**Comment by kubilaycaglayan** [comment]
Hello Rose :hand: 

Thanks for your presentation... :fireworks: 

In your routes:
You probably like to redirect the client to some path in any kind of situation.
For example what if the client puts `/something` in the address bar?
Please check my repository to see how I solved this problem => [routes.rb](https://github.com/kubilaycaglayan/reporting-scientists/blob/development/config/routes.rb)

Notice last 2 lines:

```
  root to: 'sessions#new'
  get '*path' => redirect('/')
```

With all my respect...
